### ISSUE TITLE
SAT&SATshared

### ISSUE THREAD

**Issue by kaijieshi7** [eghouti/SAL#2]
what's the difference between 'sat.py' and 'satshared.py'

**Comment by eghouti** [comment]
The difference is: let say we have for one convolution layer a tensor weigh W [C_in,C_out,H,W]. in sat.py we can have a different position of the kept weight for each kernel W[cin,cout]. in satshared.py the kernels W[cin,:] shared the same position of the kept weight for all cout in C_out. Reported results in the payer use the sat.py version.

**Comment by kaijieshi7** [comment]
OK, 3Q.You got up early.I'm live in China, and i'm going to have dinner and go to sleep.😁
